global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

scrape_configs:
  # AI Platform Backend
  - job_name: 'ai-platform-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # AI Platform Celery Worker (disabled - no metrics endpoint configured)
  # - job_name: 'ai-platform-celery'
  #   static_configs:
  #     - targets: ['celery-worker:8002']
  #   metrics_path: '/metrics'
  #   scrape_interval: 10s
  #   scrape_timeout: 5s

  # System Metrics (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # GPU Metrics (NVIDIA DCGM Exporter) - disabled, not configured
  # - job_name: 'dcgm-exporter'
  #   static_configs:
  #     - targets: ['dcgm-exporter:9400']
  #   scrape_interval: 15s

  # MongoDB Metrics - disabled, exporter not configured
  # - job_name: 'mongodb-exporter'
  #   static_configs:
  #     - targets: ['mongodb-exporter:9216']
  #   scrape_interval: 30s

  # Redis Metrics - disabled, exporter not configured
  # - job_name: 'redis-exporter'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #   scrape_interval: 30s

  # MinIO Metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Training Job Metrics - disabled until metrics endpoints are implemented
  # - job_name: 'training-jobs'
  #   static_configs:
  #     - targets: ['backend:8001']
  #   metrics_path: '/api/v1/monitoring/training-metrics'
  #   scrape_interval: 30s
  #   scrape_timeout: 10s

  # Model Performance Metrics - disabled until metrics endpoints are implemented
  # - job_name: 'model-performance'
  #   static_configs:
  #     - targets: ['backend:8001']
  #   metrics_path: '/api/v1/monitoring/model-metrics'
  #   scrape_interval: 60s
  #   scrape_timeout: 15s
